LOG_SCHEMAS = {
    "ATMA": {
        "timestamp": str,
        "log_level": str,
        "atm_id": str,
        "location_code": str,
        "session_id": (str, type(None)),
        "correlation_id": (str, type(None)),
        "transaction_id": (str, type(None)),
        "event_type": str,
        "message": str,
        "component": str,
        "thread_id": (int, type(None)),
        "response_time_ms": (int, type(None)),
        "error_code": (str, type(None)),
        "error_detail": (str, type(None)),
        "atm_status": str,
        "os_version": (str, type(None)),
        "app_version": str,
        "_anomaly": (str, type(None))
    },
    "ATMH": {
        "timestamp": str,
        "atm_id": str,
        "correlation_id": (str, type(None)),
        "component": str,
        "event_type": str,
        "severity": str,
        "message": str,
        "metric_name": (str, type(None)),
        "metric_value": (int, float, type(None)),
        "metric_unit": (str, type(None)),
        "threshold_value": (int, float, type(None)),
        "firmware_version": (str, type(None)),
        "_anomaly": (str, type(None))
    },
    "TERM": {
        "timestamp": str,
        "log_level": str,
        "service_name": str,
        "service_version": str,
        "container_id": (str, type(None)),
        "pod_name": (str, type(None)),
        "correlation_id": (str, type(None)),
        "transaction_id": (str, type(None)),
        "atm_id": (str, type(None)),
        "event_type": str,
        "message": str,
        "logger_name": (str, type(None)),
        "thread_name": (str, type(None)),
        "response_time_ms": (int, type(None)),
        "http_status_code": (int, type(None)),
        "exception_class": (str, type(None)),
        "exception_message": (str, type(None)),
        "db_query_time_ms": (int, type(None)),
        "environment": str,
        "_anomaly": (str, type(None))
    },
    "KAFK": {
        "timestamp": str,
        "event_id": str,
        "correlation_id": (str, type(None)),
        "atm_id": str,
        "atm_status": str,
        "transaction_rate_tps": (int, float),
        "response_time_ms": int,
        "transaction_volume": int,
        "transaction_success_rate": (int, float),
        "transaction_failure_reason": (str, type(None)),
        "failure_count": int,
        "window_duration_seconds": int,
        "kafka_partition": (int, type(None)),
        "kafka_offset": (int, type(None)),
        "_anomaly": (str, type(None))
    },
    "PROM": {
        "timestamp": str,
        "metric_name": str,
        "metric_type": str,
        "metric_value": (int, float),
        "service_name": str,
        "pod_name": (str, type(None)),
        "container_id": (str, type(None)),
        "label_area": (str, type(None)),
        "label_env": (str, type(None)),
        "help_text": (str, type(None)),
        "_anomaly": (str, type(None))
    },
    "WINOS": {
        "timestamp": str,
        "atm_id": str,
        "hostname": str,
        "os_version": (str, type(None)),
        "cpu_usage_percent": (int, float),
        "memory_used_mb": (int, float),
        "memory_total_mb": (int, float),
        "memory_usage_percent": (int, float, type(None)),
        "disk_read_bytes_per_sec": (int, float, type(None)),
        "disk_write_bytes_per_sec": (int, float, type(None)),
        "disk_free_gb": (int, float),
        "network_bytes_sent_per_sec": (int, float, type(None)),
        "network_bytes_recv_per_sec": (int, float, type(None)),
        "network_errors": (int, type(None)),
        "process_count": (int, type(None)),
        "system_uptime_seconds": (int, type(None)),
        "event_log_errors_last_min": (int, type(None)),
        "_anomaly": (str, type(None))
    },
    "GCP": {
        "timestamp": str,
        "project_id": str,
        "resource_type": str,
        "resource_id": str,
        "zone": (str, type(None)),
        "metric_name": str,
        "metric_value": (int, float),
        "metric_unit": (str, type(None)),
        "cpu_usage_percent": (int, float, type(None)),
        "memory_usage_bytes": (int, type(None)),
        "memory_limit_bytes": (int, type(None)),
        "network_ingress_bytes": (int, type(None)),
        "network_egress_bytes": (int, type(None)),
        "restart_count": (int, type(None)),
        "label_app": (str, type(None)),
        "label_env": (str, type(None)),
        "label_version": (str, type(None)),
        "_anomaly": (str, type(None))
    }
}